setec_gdoc:
    resource: "@SetecGdocBundle/Resources/config/routing.yml"
    prefix:   /gdoc

setec_annuaire:
    resource: "@SetecAnnuaireBundle/Resources/config/routing.yml"
    prefix:   /annuaire

setec_intranet:
    resource: "@SetecIntranetBundle/Resources/config/routing.yml"
    prefix:   /intranet

setec_baseco:
    resource: "@SetecBasecoBundle/Resources/config/routing.yml"
    prefix:   /baseco

setec_affelec:
    resource: "@SetecAffelecBundle/Resources/config/routing.yml"
    prefix:   /affelec

sdz_blog:
    resource: "@SdzBlogBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password