parameters:
#    setec_dos_aff_elec.example.class: Setec\AffelecBundle\Example

services:
#    setec_dos_aff_elec.example:
#        class: %setec_dos_aff_elec.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
