<?php

namespace Setec\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EntiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntiteRepository extends EntityRepository
{
}
