<?php

namespace Setec\SalarieBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SalarieEntiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalarieEntiteRepository extends EntityRepository
{
}
